### ISSUE TITLE
How to resolve if we have project with repository uses cassandraTemplate and ReactiveCassandraTemplate

### ISSUE THREAD

**Issue by tejaswi212** [spring-projects/spring-data-cassandra#1265] opened 2022-05-12 20:35 UTC
**Failed to convert property value of type 'org.springframework.data.cassandra.core.ReactiveCassandraTemplate' to required type 'org.springframework.data.cassandra.core.CassandraTemplate' for property 'cassandraTemplate'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'org.springframework.data.cassandra.core.ReactiveCassandraTemplate' to required type** 'org.springframework.data.cassandra.core.CassandraTemplate' for property 'cassandraTemplate': no matching editors or conversion strategy found
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)

**Comment by mp911de** [comment] 2022-05-16 05:59
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-05-23 05:59
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-05-30 06:04
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-05-30 06:04 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
