### ISSUE TITLE
 ID mismatch while trying to reprepare

### ISSUE THREAD

**Issue by gasperlf** [spring-projects/spring-data-cassandra#1276] opened 2022-06-08 15:52 UTC
I'm using CassandraOperations and getting this error sometimes 

_java.lang.IllegalStateException: ID mismatch while trying to reprepare (expected 0x344e695e7952944481f0a52dcaed6639, got 0x993290193b3f9819d9ba755c94394729). This prepared statement won't work anymore. This usually happens when you run a 'USE...' query after the statement was prepared.
	at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler$NodeResponseCallback.lambda$processErrorResponse$3(CqlRequestHandler.java:733)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at com.datastax.oss.driver.internal.core.adminrequest.AdminRequestHandler.setFinalResult(AdminRequestHandler.java:200)
	at com.datastax.oss.driver.internal.core.adminrequest.ThrottledAdminRequestHandler.setFinalResult(ThrottledAdminRequestHandler.java:158)
	at com.datastax.oss.driver.internal.core.adminrequest.AdminRequestHandler.onResponse(AdminRequestHandler.java:190)
	at com.datastax.oss.driver.internal.core.channel.InFlightHandler.channelRead(InFlightHandler.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)_

**Comment by mp911de** [comment] 2022-06-13 08:15
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-06-20 08:19
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-06-27 08:19
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-06-27 08:19 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
