### ISSUE TITLE
Regression in support of sort in queries [DATACASS-842]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-cassandra#1008] opened 2020-12-31 10:15 UTC
**[Luc Boutier](https://jira.spring.io/secure/ViewProfile.jspa?name=luc)** opened **[DATACASS-842](https://jira.spring.io/browse/DATACASS-842?redirect=false)** and commented

When migrating a project from cassandra 2.x to 3.x I encountered an issue in the ordering of sort parameters.
The clustering key of my object contains (in order) fields repairOrderId and revisionId and I was using the following query

val query = query(where("partitionKey").`is`(partitionKey)).sort(by(DESC, "repairOrderId", "revisionId"))
return cassandraTemplate.selectOne(query, RepairOrderByBasket::class.java)

It seems that somehow the sort is mixing up and creates a statement with 

```java
ORDER BY revisionId DESC, repairOrderId DESC
```

that cassandra does not support (it requires the same order as clustering keys so 

```java
ORDER BY repairOrderId DESC, revisionId DESC
```

In my particular case it was actually just better to use a clustering ordering on the table definition rather than at the query level but I guess this can be an issue in some other context

---
No further details from [DATACASS-842](https://jira.spring.io/browse/DATACASS-842?redirect=false)

**Comment by mp911de** [comment] 2021-01-29 10:31
Thanks for the report @lucboutier. That's caused by collecting sort orders in a `Map` which messes up the actual order of sort-by properties.

**Comment by mp911de** [comment] 2021-01-29 10:54
That's fixed now.

**Closed by mp911de** 2021-01-29 10:54 UTC
Labels: type: regression

**Comment by lucboutier** [comment] 2021-01-29 10:56
Amazing! Thanks a lot for the great work!
